[package]
name = "ttuydm"
version = "0.0.0-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.21"
ncurses = "6.0.0"
pam-client = "0.5.0"
serde_yaml = "0.9.34"
